modLoader="javafml"
loaderVersion="[35,)"
license="Direct"

[[mods]]
modId="mod_jadenslore"
version="1.5.0"
displayName="Jaden's Lore"
credits="Make sure to go check out Andre's YouTube channel or the videos I made with him at the YouTube channel JadensWebDOOM! Also I took mod time craft game from a convo a friend, FinDrew and I had not too long ago. Thought it would fit in quite well."
displayURL="http://jadenswebmc.us.to/jadensmod/"
logoFile="logo.png"
authors="JadensWebMC, JadensWeb, Andre, MrFinDrew"
description='''
Hey, guys and gals. This mod was created by JadensWebMC and is owned by JadensWeb. I made this mod because I love a lot of the funny moments I have with some people, you know who you are, and boom, made a mod around said funny moments.
'''

[[dependencies.mod_jadenslore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




